MekanKesfi/MekanKesfiWebUI/Models/UrunlerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static MekanKesfi.Dto.Dto.UrunlerDTO;

namespace MekanKesfiWebUI.Models
{
    public class UrunlerViewModel
    {
        public List<UrunMekanDTO> UrunListe { get; set; }
        public UrunDetayDTO UrunDetay { get; set; }
    }
}

MekanKesfi/MekanKesfiWebUI/Controllers/MekanlarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MekanKesfi.Business.Abstract;
using MekanKesfiWebUI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static MekanKesfi.Dto.Dto.IllerDTO;
using static MekanKesfi.Dto.Dto.MekanlarDTO;
using static MekanKesfi.Dto.Dto.ReklamlarDTO;
using static MekanKesfi.Dto.Dto.UrunlerDTO;

namespace MekanKesfiWebUI.Controllers
{
    public class MekanlarController : Controller
    {
        private IMekanlarService _serviceMekan;
        private MekanlarViewModel _model;
        private IUrunlerService _serviceUrun;
        private IMapper _mapper;
        private IReklamlarService _serviceReklam;
        private IIllerService _serviceIl;
        private IIlcelerService _serviceIlce;

        public MekanlarController(IMekanlarService serviceMekan, MekanlarViewModel model,
            IUrunlerService serviceUrun, IMapper mapper, IReklamlarService serviceReklam,
            IIllerService serviceIl, IIlcelerService serviceIlce)
        {
            _serviceMekan = serviceMekan;
            _model = model;
            _serviceUrun = serviceUrun;
            _mapper = mapper;
            _serviceReklam = serviceReklam;
            _serviceIl = serviceIl;
            _serviceIlce = serviceIlce;
        }

        public async Task<IActionResult> Liste(string aranan)
        {
            _model.MekanListe = _mapper.Map<List<MekanlarListeDTO>>(await _serviceMekan.GetMekanListe(aranan));           
            
            return View(_model);
        }


        public async Task<IActionResult> Detay(int mekanId)
        {
            _model.MekanDetay = _mapper.Map<MekanlarDetayDTO>(await _serviceMekan.GetMekan(mekanId));
            _model.UrunListe = _mapper.Map<List<UrunMekanDTO>>(await _serviceUrun.GetMekanUrun(mekanId));
            _model.ReklamListe = _mapper.Map<List<ReklamMekanDTO>>(await _serviceReklam.GetReklamMekan(mekanId));
            return View(_model);
        }
      
    }
}

MekanKesfi/MekanKesfiWebUI/Controllers/UrunlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MekanKesfi.Business.Abstract;
using MekanKesfiWebUI.Models;
using Microsoft.AspNetCore.Mvc;
using static MekanKesfi.Dto.Dto.UrunlerDTO;

namespace MekanKesfiWebUI.Controllers
{
    public class UrunlerController : Controller
    {
        private IMekanlarService _serviceMekan;
        private UrunlerViewModel _model;
        private IUrunlerService _serviceUrun;
        private IMapper _mapper;

        public UrunlerController(IMekanlarService serviceMekan, UrunlerViewModel model,
            IUrunlerService serviceUrun, IMapper mapper)
        {
            _serviceMekan = serviceMekan;
            _model = model;
            _serviceUrun = serviceUrun;
            _mapper = mapper;
        }

        public async Task< IActionResult> Liste()
        {
            _model.UrunListe = _mapper.Map<List<UrunMekanDTO>>(await _serviceUrun.GetUrunListe());
            return View(_model);
        }

        public async Task<IActionResult> UrunDetay(int urunId)
        {
            _model.UrunDetay = _mapper.Map<UrunDetayDTO>(await _serviceUrun.GetUrunDetay(urunId));
            return View(_model);
        }

    }
}

MekanKesfi/MekanKesfiWebUI/Views/Urunler/Liste.cshtml
@model MekanKesfiWebUI.Models.UrunlerViewModel

@{
    ViewData["Title"] = "Liste";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container">
    <div class="row">
        @foreach (var item in Model.UrunListe)
        {

            <div class="col-md-6">
                <h2 class="mt-3 pt-3">@item.UrunAd</h2>
                <div class="card mb-4 shadow-sm">
                    <img class="card-img-top"
                         src="@item.UrunFoto" style="height: 225px; width: 100%" alt="Card image cap">
                    <div class="card-body">

                        <p class="card-text">@item.UrunFiyat</p>

                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-secondary" asp-controller="Urunler" asp-action="UrunDetay" asp-route-urunId="@item.UrunId">Detay</a>
                            </div>
                            <small class="text-muted col-6" style="text-align:right">@item.IlceAd / @item.IlAd</small>
                            <small class="text-muted col-md-6">@item.MekanAd</small>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

MekanKesfi/MekanKesfiWebUI/Views/Urunler/UrunDetay.cshtml
@model MekanKesfiWebUI.Models.UrunlerViewModel

@{
    ViewData["Title"] = "UrunDetay";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-5">
            <img src="@Model.UrunDetay.UrunFoto" width="200" height="300" />
        </div>

        <div class="col-md-7">
            <h4>@Model.UrunDetay.UrunAd</h4>
            <ul class="list-group">
                <li class="list-group-item"><label class="col-md-5">Fiyat :</label><label class="col-md-7">@Model.UrunDetay.UrunFiyat</label></li>
                <li class="list-group-item"><label class="col-md-5">Mekan Adı :</label><label class="col-md-7">@Model.UrunDetay.MekanAd</label></li>
                <li class="list-group-item"><label class="col-md-5">İlçe / İl :</label><label class="col-md-7">@Model.UrunDetay.IlceAd / @Model.UrunDetay.IlAd</label></li>
                <a class="btn btn-sm btn-outline-secondary col-md-5" asp-controller="Mekanlar" asp-action="Detay" asp-route-mekanId="@Model.UrunDetay.MekanId ">Satılan Mekana Git</a>
            </ul>
        </div>
    </div>
 
</div>